name: Test optimize_image
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
  pull_request:
  workflow_dispatch:

jobs:
  optimized:
    runs-on: ubuntu-latest
    outputs:
      imgsize: ${{ steps.compress.outputs.imgsize }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./ # pguyot/arm-runner-action@HEAD
      id: optimized
      with:
        base_image: raspios_lite:2021-05-07
        optimize_image: yes
        commands: |
            cat /dev/random > /rand || rm /rand
    - name: Check if optimized image contains both the boot and root partitions
      run: |
        function assert_has_partition() {
          if ! fdisk -l ${{ steps.optimized.outputs.image }} | grep "\.img$1.*$2"; then
            echo "Test Failed! Missing partition $1: $2"
            exit 1
          else
            echo "Test OK: found partition $1: $2"
          fi
        }

        fdisk -l ${{ steps.optimized.outputs.image }}

        assert_has_partition 1 "W95 FAT32"
        assert_has_partition 2 "Linux"
    - name: Compress image
      id: compress
      run: |
        mv ${{ steps.optimized.outputs.image }} /home/actions/temp/optimized-image.img
        gzip /home/actions/temp/optimized-image.img
        imgsize=`stat --printf="%s" /home/actions/temp/optimized-image.img.gz`
        echo "imgsize=${imgsize}" >> $GITHUB_OUTPUT
  unoptimized:
    runs-on: ubuntu-latest
    outputs:
      imgsize: ${{ steps.compress.outputs.imgsize }}
    steps:
    - uses: actions/checkout@v4
    - uses: ./ # pguyot/arm-runner-action@HEAD
      id: unoptimized
      with:
        base_image: raspios_lite:2021-05-07
        optimize_image: no
        commands: |
            cat /dev/random > /rand || rm /rand
    - name: Check if unoptimized image contains both the boot and root partitions
      run: |
        function assert_has_partition() {
          if ! fdisk -l ${{ steps.unoptimized.outputs.image }} | grep "\.img$1.*$2"; then
            echo "Test Failed! Missing partition $1: $2"
            exit 1
          else
            echo "Test OK: found partition $1: $2"
          fi
        }

        fdisk -l ${{ steps.unoptimized.outputs.image }}

        assert_has_partition 1 "W95 FAT32"
        assert_has_partition 2 "Linux"
    - name: Compress image
      id: compress
      run: |
        mv ${{ steps.unoptimized.outputs.image }} /home/actions/temp/unoptimized-image.img
        gzip /home/actions/temp/unoptimized-image.img
        imgsize=`stat --printf="%s" /home/actions/temp/unoptimized-image.img.gz`
        echo "imgsize=${imgsize}" >> $GITHUB_OUTPUT
  compare:
    runs-on: ubuntu-latest
    needs: [optimized, unoptimized]
    steps:
    - name: Test image sizes
      run: |
        echo "Optimized size: ${{needs.optimized.outputs.imgsize}}"
        echo "Unoptimized size: ${{needs.unoptimized.outputs.imgsize}}"
        test $(( ${{needs.unoptimized.outputs.imgsize}} - ${{needs.optimized.outputs.imgsize}} )) > 300000000
